// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Ng-LiQ2GB5DdXI5puARtGcb_nX6HpUs',
    appId: '1:150961179259:web:11e49c03a6ded40516f0de',
    messagingSenderId: '150961179259',
    projectId: 'mrsos-31341',
    authDomain: 'mrsos-31341.firebaseapp.com',
    storageBucket: 'mrsos-31341.firebasestorage.app',
    measurementId: 'G-ZBKMJ5XN6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBldDhQTtf-Tn_52kLnllT3R36JNogyAuQ',
    appId: '1:150961179259:android:41485cf79d95170616f0de',
    messagingSenderId: '150961179259',
    projectId: 'mrsos-31341',
    storageBucket: 'mrsos-31341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuMQdEqT7LXgRgJ0GbHoEzro1Q3s2Mpp0',
    appId: '1:150961179259:ios:406dcc4916e9147716f0de',
    messagingSenderId: '150961179259',
    projectId: 'mrsos-31341',
    storageBucket: 'mrsos-31341.firebasestorage.app',
    iosBundleId: 'com.example.mrsos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuMQdEqT7LXgRgJ0GbHoEzro1Q3s2Mpp0',
    appId: '1:150961179259:ios:406dcc4916e9147716f0de',
    messagingSenderId: '150961179259',
    projectId: 'mrsos-31341',
    storageBucket: 'mrsos-31341.firebasestorage.app',
    iosBundleId: 'com.example.mrsos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Ng-LiQ2GB5DdXI5puARtGcb_nX6HpUs',
    appId: '1:150961179259:web:84548c1f0c814d3216f0de',
    messagingSenderId: '150961179259',
    projectId: 'mrsos-31341',
    authDomain: 'mrsos-31341.firebaseapp.com',
    storageBucket: 'mrsos-31341.firebasestorage.app',
    measurementId: 'G-KSHYFB7M0C',
  );
}
